//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Kho.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HangTonEntities : DbContext
    {
        public HangTonEntities()
            : base("name=HangTonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_Nhaphang(Nullable<int> manhap, Nullable<int> maMH, Nullable<int> soluongNhap, Nullable<double> gianhap, Nullable<double> tongtien)
        {
            var manhapParameter = manhap.HasValue ?
                new ObjectParameter("Manhap", manhap) :
                new ObjectParameter("Manhap", typeof(int));
    
            var maMHParameter = maMH.HasValue ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(int));
    
            var soluongNhapParameter = soluongNhap.HasValue ?
                new ObjectParameter("SoluongNhap", soluongNhap) :
                new ObjectParameter("SoluongNhap", typeof(int));
    
            var gianhapParameter = gianhap.HasValue ?
                new ObjectParameter("Gianhap", gianhap) :
                new ObjectParameter("Gianhap", typeof(double));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("Tongtien", tongtien) :
                new ObjectParameter("Tongtien", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Nhaphang", manhapParameter, maMHParameter, soluongNhapParameter, gianhapParameter, tongtienParameter);
        }
    }
}
